tutors-project/src/Entity/University.php
<?php

namespace App\Entity;

use App\Repository\UniversityRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UniversityRepository::class)]
class University
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $university_name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUniversityName(): ?string
    {
        return $this->university_name;
    }

    public function setUniversityName(string $university_name): self
    {
        $this->university_name = $university_name;

        return $this;
    }
}

tutors-project/src/Form/UniversityType.php
<?php

namespace App\Form;

use App\Entity\University;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UniversityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('university_name', TextType::class, [
                'attr' => ['class' => 'form-control']
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => University::class,
        ]);
    }
}

tutors-project/src/Controller/UniversityController.php
<?php

namespace App\Controller;

use App\Entity\University;
use App\Form\UniversityType;
use App\Repository\UniversityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/university')]
class UniversityController extends AbstractController
{
    #[Route('/', name: 'app_university_index', methods: ['GET'])]
    public function index(UniversityRepository $universityRepository): Response
    {
        return $this->render('university/index.html.twig', [
            'universities' => $universityRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_university_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UniversityRepository $universityRepository): Response
    {
        $university = new University();
        $form = $this->createForm(UniversityType::class, $university);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $universityRepository->save($university, true);

            return $this->redirectToRoute('app_university_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('university/new.html.twig', [
            'university' => $university,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_university_show', methods: ['GET'])]
    public function show(University $university): Response
    {
        return $this->render('university/show.html.twig', [
            'university' => $university,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_university_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, University $university, UniversityRepository $universityRepository): Response
    {
        $form = $this->createForm(UniversityType::class, $university);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $universityRepository->save($university, true);

            return $this->redirectToRoute('app_university_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('university/edit.html.twig', [
            'university' => $university,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_university_delete', methods: ['POST'])]
    public function delete(Request $request, University $university, UniversityRepository $universityRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$university->getId(), $request->request->get('_token'))) {
            $universityRepository->remove($university, true);
        }

        return $this->redirectToRoute('app_university_index', [], Response::HTTP_SEE_OTHER);
    }
}

tutors-project/templates/university/_delete_form.html.twig
<form method="post" action="{{ path('app_university_delete', {'id': university.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ university.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

tutors-project/templates/university/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-dark mt-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

tutors-project/templates/university/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit University{% endblock %}

{% block body %}
<div class="container mt-3 mb-3">
    <h1>Edit University</h1>
</div>

<div class="container">

    
    <div class="mb-2">{{ include('university/_form.html.twig', {'button_label': 'Update'}) }}</div>
    <div>{{ include('university/_delete_form.html.twig') }}</div>
        <a class="btn btn-secondary mt-2" role="button" href="{{ path('app_university_index') }}">Back to list</a>
</div>
{% endblock %}

tutors-project/templates/university/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}University{% endblock %}

{% block body %}
<h1 class="text-center mt-5 mb-5">University</h1>

<div class="container d-flex justify-content-center">
<div class="row">
  {% for university in universities %}
    <div class="col">
        <div class="card border-dark mb-3 shadow-sm p-3 mb-5 bg-body rounded" style="width: 18rem;">
            <div class="card-header fw-bold">{{ university.universityName }}</div>
              <div class="card-body d-flex">
              {# <h6 class="card-subtitle mb-2 text-muted">{{ subject.id }}</h6> #}
                <a href="{{ path('app_university_show', {'id': university.id}) }}" class="card-link btn btn-outline-success mt-2" role="button">Details</a>
                <a href="{{ path('app_university_edit', {'id': university.id}) }}" class="card-link btn btn-outline-primary mt-2" role="button">Edit</a>
              </div>
            </div>
        </div>
    {% else %}
          <div>No records found.</div>
          {% endfor %}
</div>
</div>
<div class="container d-flex justify-content-center">
  <a class="card-link btn btn-outline-dark mt-2" role="button" 
   href="{{ path('app_university_new') }}">Create new</a>
  </div>
{% endblock %}

tutors-project/templates/university/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}University{% endblock %}

{% block body %}
<div class="container" >
<h1>Create new University</h1>
</div>

<div class="container">
    <div class="card border border-0" style="width: 400px;">
    {{ include('university/_form.html.twig') }}
</div>
<a class="card-link btn mt-2" role="button" style="background-color: rgb(163, 193, 201);" href="{{ path('app_university_index') }}">Back to list</a>
</div>

{% endblock %}

tutors-project/templates/university/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}University{% endblock %}

{% block body %}
<h1 class="text-center mt-5 mb-5">Details</h1>

<div class="container d-flex justify-content-center">
<div class="row">
    <div class="col-sm-6">
        <div class="card border-dark mb-3 shadow-sm p-3 mb-5 bg-body rounded" style="width: 18rem;">
            <div class="card-header fw-bold">{{ university.universityName }}</div>
            <div class="card-body">
              <h6 class="card-subtitle mb-2 text-muted">University ID: {{ university.id }}</h6>
              <br>
                    <a style="background-color: rgb(116, 200, 221);"  href="{{ path('app_university_edit', {'id': university.id}) }}" class="card-link btn " role="button">Edit</a>
               <br><br>
                    <a class="card-link btn" role="button" style="background-color: rgb(163, 193, 201);" 
                    href="{{ path('app_university_index') }}">Go back to the list.</a>
            </div>
          </div>
    </div>
</div>
</div>
<div class="container d-flex justify-content-center">
    {{ include('university/_delete_form.html.twig') }}
    </div>

{% endblock %}