tutors-project/src/Entity/UniqueContent.php
<?php

namespace App\Entity;

use App\Repository\UniqueContentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UniqueContentRepository::class)]
class UniqueContent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 31)]
    private ?string $first_name = null;

    #[ORM\Column(length: 63)]
    private ?string $last_name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 63)]
    private ?string $tut_pic = null;

    #[ORM\Column(length: 63)]
    private ?string $bg_pic = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTutPic(): ?string
    {
        return $this->tut_pic;
    }

    public function setTutPic(string $tut_pic): self
    {
        $this->tut_pic = $tut_pic;

        return $this;
    }

    public function getBgPic(): ?string
    {
        return $this->bg_pic;
    }

    public function setBgPic(string $bg_pic): self
    {
        $this->bg_pic = $bg_pic;

        return $this;
    }
}

tutors-project/src/Form/UniqueContentType.php
<?php

namespace App\Form;

use App\Entity\UniqueContent;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class UniqueContentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('first_name', TextType::class, [
                'attr' => ['class' => 'form-control border border-dark p-2 mb-3']
            ])
            ->add('last_name', TextType::class, [
                'attr' => ['class' => 'form-control border border-dark p-2 mb-3']
            ])
            ->add('description' , TextareaType::class, [
                'attr' => ['class' => 'form-control border border-dark p-2 mb-3']
            ])
            ->add('tut_pic',FileType::class,[
                'attr' => ['class' => 'form-control border border-dark p-2 mb-3'],
                'label' => 'TuT_Pic (PDF file)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' =>'2048k',
                        'mimeTypes' =>[
                            'image/png',
                            'image/jpg',
                            'image/jpeg',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid picture',
                    ])
                ]
            ])
            ->add('bg_pic', FileType::class,[
                'attr' => ['class' => 'form-control border border-dark p-2 mb-3'],
                'label' => 'BG_Pic (PDF file)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' =>'2048k',
                        'mimeTypes' =>[
                            'image/png',
                            'image/jpg',
                            'image/jpeg',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid picture',
                    ])
                ]
            ] );
}

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => UniqueContent::class,
        ]);
    }
}

tutors-project/src/Controller/UniqueContentController.php
<?php

namespace App\Controller;

use App\Entity\UniqueContent;
use App\Form\UniqueContentType;
use App\Repository\UniqueContentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;

#[Route('/unique/content')]
class UniqueContentController extends AbstractController
{
    #[Route('/', name: 'app_unique_content_index', methods: ['GET'])]
    public function index(UniqueContentRepository $uniqueContentRepository): Response
    {
        return $this->render('unique_content/index.html.twig', [
            'unique_contents' => $uniqueContentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_unique_content_new', methods: ['GET', 'POST'])]
    public function new (Request $request, UniqueContentRepository $uniqueContentRepository, SluggerInterface $slugger): Response
    {
        $uniqueContent = new UniqueContent();
        $form = $this->createForm(UniqueContentType::class, $uniqueContent);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            $ImageFile = $form->get('tut_pic')->getData();
            $BgPicFile = $form->get('bg_pic')->getData();

            if ($ImageFile && $BgPicFile) {
                $originalFilename = pathinfo($ImageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $originalFilename = pathinfo($BgPicFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $ImageFile->guessExtension();
                $newerFilename = $safeFilename . '-' . uniqid() . '.' . $BgPicFile->guessExtension();
                try {
                    $ImageFile->move(
                        // $this->getParameter('images_directory'),
                        "images/",
                        $newFilename
                    );
                    $BgPicFile->move(
                        // $this->getParameter('images_directory'),
                        "images/",
                        $newerFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $uniqueContent->setTutPic($newFilename);
                $uniqueContent->setBgPic($newerFilename);
                $uniqueContentRepository->save($uniqueContent, true);

            }


            return $this->redirectToRoute('app_unique_content_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('unique_content/new.html.twig', [
            'unique_content' => $uniqueContent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_unique_content_show', methods: ['GET'])]
    public function show(UniqueContent $uniqueContent): Response
    {
        return $this->render('unique_content/show.html.twig', [
            'unique_content' => $uniqueContent,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_unique_content_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, UniqueContent $uniqueContent, UniqueContentRepository $uniqueContentRepository, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(UniqueContentType::class, $uniqueContent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ImageFile = $form->get('tut_pic')->getData();
            $BgPicFile = $form->get('bg_pic')->getData();

            if ($ImageFile || $BgPicFile) {
                if ($ImageFile) {
                    $originalFilename = pathinfo($ImageFile->getClientOriginalName(), PATHINFO_FILENAME);
                    $safeFilename = $slugger->slug($originalFilename);
                    $newFilename = $safeFilename . '-' . uniqid() . '.' . $ImageFile->guessExtension();

                }
                if ($BgPicFile) {
                    $originalFilename = pathinfo($BgPicFile->getClientOriginalName(), PATHINFO_FILENAME);
                    $safeFilename = $slugger->slug($originalFilename);
                    $newerFilename = $safeFilename . '-' . uniqid() . '.' . $BgPicFile->guessExtension();
                }



                try {
                    if ($ImageFile) {
                        $ImageFile->move(
                            // $this->getParameter('images_directory'),
                            "images/",
                            $newFilename
                        );
                    }
                    if ($BgPicFile) {
                        $BgPicFile->move(
                            // $this->getParameter('images_directory'),
                            "images/",
                            $newerFilename
                        );
                    }
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                if ($ImageFile) {
                    $uniqueContent->setTutPic($newFilename);
                }
                if ($BgPicFile) {
                    $uniqueContent->setBgPic($newerFilename);
                }

                $uniqueContentRepository->save($uniqueContent, true);

            }


            return $this->redirectToRoute('app_unique_content_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('unique_content/edit.html.twig', [
            'unique_content' => $uniqueContent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_unique_content_delete', methods: ['POST'])]
    public function delete(Request $request, UniqueContent $uniqueContent, UniqueContentRepository $uniqueContentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $uniqueContent->getId(), $request->request->get('_token'))) {
            $uniqueContentRepository->remove($uniqueContent, true);
        }

        return $this->redirectToRoute('app_unique_content_index', [], Response::HTTP_SEE_OTHER);
    }
}

tutors-project/templates/unique_content/_delete_form.html.twig
<form method="post" action="{{ path('app_unique_content_delete', {'id': unique_content.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ unique_content.id) }}">
    <button class="btn btn-outline-danger mt-2">Delete</button>
</form>

tutors-project/templates/unique_content/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-success mt-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

tutors-project/templates/unique_content/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Content{% endblock %}

{% block body %}

<div class="container mt-3 mb-3">
    <h3>Edit Content</h3>
</div>

    <div class="container">
        <div class="card border border-0" style="width: 600px;">
    {{ include('unique_content/_form.html.twig', {'button_label': 'Update'}) }}
   
    {{ include('unique_content/_delete_form.html.twig') }}
</div>
<a class="btn btn-outline-secondary mt-2 mb-2" role="button" href="{{ path('app_unique_content_index') }}">Back to the list</a>

    </div>
{% endblock %}

tutors-project/templates/unique_content/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Unique Content{% endblock %}

{% block body %}
    <h3 class="text-center mb-4">Unique Content</h3>
    <div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>First_name</th>
                <th>Last_name</th>
                <th>Description</th>
                <th>Tut_pic</th>
                <th>Bg_pic</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for unique_content in unique_contents %}
            <tr>
                <td>{{ unique_content.id }}</td>
                <td>{{ unique_content.firstName }}</td>
                <td>{{ unique_content.lastName }}</td>
                <td>{{ unique_content.description }}</td>
                <td><img style="width: 130px;" class="card-img-top" src="{{asset("images/" ~ unique_content.tutPic)}}" alt="Card image cap"></td>
                <td><img style="width: 130px;" class="card-img-top" src="{{asset("images/" ~ unique_content.bgPic)}}" alt="Card image cap"></td>
                <td>
                    <a class="card-link btn btn-outline-success mt-2" role="button" href="{{ path('app_unique_content_show', {'id': unique_content.id}) }}">Show</a>
                    <a class="card-link btn btn-outline-primary mt-2" role="button" href="{{ path('app_unique_content_edit', {'id': unique_content.id}) }}">Edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a class="card-link btn btn-outline-dark mt-2" role="button" href="{{ path('app_unique_content_new') }}">Create new</a>
</div>

{% endblock %}

tutors-project/templates/unique_content/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New UniqueContent{% endblock %}

{% block body %}
<div class="container mt-3 mb-3">
    <h1>Create new UniqueContent</h1>
    </div>

<div class="container">
    <div class="card border border-0" style="width: 600px;">
    {{ include('unique_content/_form.html.twig') }}
    </div>
    <a class="card-link btn btn-outline-secondary mt-2" role="button" href="{{ path('app_unique_content_index') }}">Back to list</a>
</div>

{% endblock %}

tutors-project/templates/unique_content/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}UniqueContent{% endblock %}

{% block body %}
<div class="container mt-3 mb-3">
    <h1>UniqueContent</h1>
</div>

<div class="container">
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ unique_content.id }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ unique_content.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ unique_content.lastName }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ unique_content.description }}</td>
            </tr>
            <tr>
                <th>Tut_pic</th>
                <td>{{ unique_content.tutPic }}</td>
            </tr>
            <tr>
                <th>Bg_pic</th>
                <td>{{ unique_content.bgPic }}</td>
            </tr>
        </tbody>
    </table>

    <a class="card-link btn btn-outline-secondary mt-2" role="button"  href="{{ path('app_unique_content_index') }}">Back to list</a>

    <a class="card-link btn btn-outline-primary mt-2 mb-2" role="button"  href="{{ path('app_unique_content_edit', {'id': unique_content.id}) }}">Edit</a>

    {{ include('unique_content/_delete_form.html.twig') }}

</div>
{% endblock %}