tutors-project/src/Entity/CardContent.php
<?php

namespace App\Entity;

use App\Repository\CardContentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CardContentRepository::class)]
class CardContent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 63)]
    private ?string $card_title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $card_text = null;

    #[ORM\Column(length: 63)]
    private ?string $card_pic = null;

    #[ORM\ManyToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?University $fk_university = null;

    #[ORM\ManyToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Subject $fk_subject = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCardTitle(): ?string
    {
        return $this->card_title;
    }

    public function setCardTitle(string $card_title): self
    {
        $this->card_title = $card_title;

        return $this;
    }

    public function getCardText(): ?string
    {
        return $this->card_text;
    }

    public function setCardText(string $card_text): self
    {
        $this->card_text = $card_text;

        return $this;
    }

    public function getCardPic(): ?string
    {
        return $this->card_pic;
    }

    public function setCardPic(string $card_pic): self
    {
        $this->card_pic = $card_pic;

        return $this;
    }

    public function getFkUniversity(): ?University
    {
        return $this->fk_university;
    }

    public function setFkUniversity(University $fk_university): self
    {
        $this->fk_university = $fk_university;

        return $this;
    }

    public function getFkSubject(): ?Subject
    {
        return $this->fk_subject;
    }

    public function setFkSubject(Subject $fk_subject): self
    {
        $this->fk_subject = $fk_subject;

        return $this;
    }
}

tutors-project/src/Form/CardContentType.php
<?php

namespace App\Form;

use App\Entity\Subject;
use App\Entity\CardContent;
use App\Entity\University;
use App\Repository\CardContentRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class CardContentType extends AbstractType
{    
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('card_title', TextType::class, [
                'attr' => ['class' => 'form-control border border-dark', 'style' => 'margin-bottom:15px'],
            ])
            ->add('card_text', TextType::class, [
                'attr' => ['class' => 'form-control border border-dark', 'style' => 'margin-bottom:15px'],
            ])
            ->add('card_pic', FileType::class,[
                'attr' => ['class' => 'form-control border border-dark', 'style' => 'margin-bottom:15px'],
                'label' => 'image (PDF file)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' =>'1024k',
                        'mimeTypes' =>[
                            'image/png',
                            'image/jpg',
                            'image/jpeg',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid picture',
                    ])
                ]
            ])
            ->add('fk_university', EntityType::class,
             ['class' => University::class,'choice_label' => 'universityName', 'attr' => ['class' => 'form-control my-1 mb-2 w-50']])

            ->add('fk_subject', EntityType::class, 
            ['class' => Subject::class,'choice_label' =>'subject_name', 'attr' => ['class' => 'form-control my-1 mb-2 w-50']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CardContent::class,
        ]);
    }
}

tutors-project/src/Controller/CardContentController.php
<?php

namespace App\Controller;

use App\Entity\CardContent;
use App\Form\CardContentType;
use App\Repository\CardContentRepository;
use App\Repository\UniversityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;

#[Route('/card/content')]
class CardContentController extends AbstractController
{
    #[Route('/', name: 'app_card_content_index', methods: ['GET'])]
    public function index(CardContentRepository $cardContentRepository): Response
    {
        return $this->render('card_content/index.html.twig', [
            'card_contents' => $cardContentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_card_content_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CardContentRepository $cardContentRepository, UniversityRepository $universityRepository,SluggerInterface $slugger): Response
    {
        $cardContent = new CardContent();
        $form = $this->createForm(CardContentType::class, $cardContent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $ImageFile = $form->get('card_pic')->getData();

            if ($ImageFile){
                $originalFilename = pathinfo($ImageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$ImageFile->guessExtension();
                try {
                    $ImageFile->move(
                        // $this->getParameter('images_directory'),
                        "images/",
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $cardContent->setCardPic($newFilename);
                $cardContentRepository->save($cardContent, true);
                
            }

            return $this->redirectToRoute('app_card_content_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('card_content/new.html.twig', [
            'card_content' => $cardContent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_card_content_show', methods: ['GET'])]
    public function show(CardContent $cardContent): Response
    {
        return $this->render('card_content/show.html.twig', [
            'card_content' => $cardContent,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_card_content_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, CardContent $cardContent, CardContentRepository $cardContentRepository, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(CardContentType::class, $cardContent);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $ImageFile = $form->get('card_pic')->getData();

            if ($ImageFile){
                $originalFilename = pathinfo($ImageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$ImageFile->guessExtension();
                try {
                    $ImageFile->move(
                        // $this->getParameter('images_directory'),
                        "images/",
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $cardContent->setCardPic($newFilename);
                $cardContentRepository->save($cardContent, true);
                
            }

            return $this->redirectToRoute('app_card_content_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('card_content/edit.html.twig', [
            'card_content' => $cardContent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_card_content_delete', methods: ['POST'])]
    public function delete(Request $request, CardContent $cardContent, CardContentRepository $cardContentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cardContent->getId(), $request->request->get('_token'))) {
            $cardContentRepository->remove($cardContent, true);
        }

        return $this->redirectToRoute('app_card_content_index', [], Response::HTTP_SEE_OTHER);
    }
}

tutors-project/templates/card_content/_delete_form.html.twig
<form method="post" action="{{ path('app_card_content_delete', {'id': card_content.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ card_content.id) }}">
    <button class="btn btn-outline-danger mt-2" >Delete</button>
</form>

tutors-project/templates/card_content/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

tutors-project/templates/card_content/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit CardContent{% endblock %}

{% block body %}
<div class="container mt-2 mb-2">
    <h1>Edit CardContent</h1>
</div>

    <div class="container">
        <div class="card p-4 border border-0" style="width: 500px;">
    {{ include('card_content/_form.html.twig', {'button_label': 'Update'}) }}
    {{ include('card_content/_delete_form.html.twig') }}
<a class="btn btn-outline-secondary mt-2" role="button" href="{{ path('app_card_content_index') }}">Back to list</a>

</div>
    </div>

{% endblock %}

tutors-project/templates/card_content/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CardContent index{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center my-2">Tutorings available</h1>
    <div class="row">
        <div class="col text-center">
            <a class="btn btn-outline-success text-center w-25 my-1" href="{{ path('app_card_content_new') }}">Create a new Tutoring!</a>
        </div>    
    </div>
    <div class="row">
        {% for card_content in card_contents %}
        <div class="col-4 my-3">
            <div class="card border border-2 p-2">
                <img  style="margin-left: 30%; width: 40%; text-align:center;" class="card-img-top" src="{{asset("images/" ~ card_content.cardPic)}}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{ card_content.cardTitle }}</h5>
                    <p class="card-text">{{ card_content.cardText }}</p>
                    <div class="d-flex">
                        <a class="card-link btn btn-outline-secondary mt-2" role="button" href="{{ path('app_card_content_show', {'id': card_content.id}) }}" class="btn btn-secondary w-100">Info</a>
                    
                        <a class="card-link btn btn-outline-secondary mt-2 mx-2" role="button" href="{{ path('app_card_content_edit', {'id': card_content.id}) }}" class="btn btn-secondary w-100">Edit</a>
                    
                        {{ include('card_content/_delete_form.html.twig') }}
                    </div>
                    
                </div>
            </div>
        </div>
    
        {% else %}
            <div class="text-center my-2">There are currently no Courses available, Check again later. &#128521;</div>
        {% endfor %}
    </div>
</div>
        

    
{% endblock %}

tutors-project/templates/card_content/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New CardContent{% endblock %}

{% block body %}
<div class="container">
    <h1>Create new CardContent</h1>
</div>

<div class="container">
    {{ include('card_content/_form.html.twig') }}
    <a class="card-link btn btn-outline-secondary mt-3" href="{{ path('app_card_content_index') }}">Back to list</a>
</div>

{% endblock %}

tutors-project/templates/card_content/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}CardContent{% endblock %}

{% block body %}
<div class="container">

    <h1>Card Content</h1>
</div>

<div class="container">

    <div class="col-4 my-3">
        <div class="card border border-0">
            <img style="width: 130px; text-align:center;" class="card-img-top" src="{{asset("images/" ~ card_content.cardPic)}}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{ card_content.cardTitle }}</h5>
                <p class="card-text">ID: {{ card_content.id }}</p>
                <p class="card-text">{{ card_content.cardText }}</p>
                        
                    <a class="card-link btn btn-outline-secondary mt-2" role="button" href="{{ path('app_card_content_edit', {'id': card_content.id}) }}" class="btn btn-secondary w-100">Edit</a>
    <a class="card-link btn btn-outline-secondary mt-3" href="{{ path('app_card_content_index') }}">Back to list</a>
                    {{ include('card_content/_delete_form.html.twig') }}
             
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}