tutors-project/src/Entity/Subject.php
<?php

namespace App\Entity;

use App\Repository\SubjectRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SubjectRepository::class)]
class Subject
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $subject_name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSubjectName(): ?string
    {
        return $this->subject_name;
    }

    public function setSubjectName(string $subject_name): self
    {
        $this->subject_name = $subject_name;

        return $this;
    }
}

tutors-project/src/Form/SubjectType.php
<?php

namespace App\Form;

use App\Entity\Subject;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SubjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('subject_name', TextType::class, [
                'attr' => ['class' => 'form-control']
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Subject::class,
        ]);
    }
}

tutors-project/src/Controller/SubjectController.php
<?php

namespace App\Controller;

use App\Entity\Subject;
use App\Form\SubjectType;
use App\Repository\SubjectRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/subject')]
class SubjectController extends AbstractController
{
    #[Route('/', name: 'app_subject_index', methods: ['GET'])]
    public function index(SubjectRepository $subjectRepository): Response
    {
        return $this->render('subject/index.html.twig', [
            'subjects' => $subjectRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_subject_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SubjectRepository $subjectRepository): Response
    {
        $subject = new Subject();
        $form = $this->createForm(SubjectType::class, $subject);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $subjectRepository->save($subject, true);

            return $this->redirectToRoute('app_subject_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('subject/new.html.twig', [
            'subject' => $subject,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_subject_show', methods: ['GET'])]
    public function show(Subject $subject): Response
    {
        return $this->render('subject/show.html.twig', [
            'subject' => $subject,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_subject_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Subject $subject, SubjectRepository $subjectRepository): Response
    {
        $form = $this->createForm(SubjectType::class, $subject);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $subjectRepository->save($subject, true);

            return $this->redirectToRoute('app_subject_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('subject/edit.html.twig', [
            'subject' => $subject,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_subject_delete', methods: ['POST'])]
    public function delete(Request $request, Subject $subject, SubjectRepository $subjectRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$subject->getId(), $request->request->get('_token'))) {
            $subjectRepository->remove($subject, true);
        }

        return $this->redirectToRoute('app_subject_index', [], Response::HTTP_SEE_OTHER);
    }
}

tutors-project/templates/subject/_delete_form.html.twig
<form method="post" action="{{ path('app_subject_delete', {'id': subject.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ subject.id) }}">
    <button class="btn btn-danger" class="card-link btn" role="button">Delete</button>
</form>

tutors-project/templates/subject/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-dark mt-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

tutors-project/templates/subject/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Subject{% endblock %}

{% block body %}
<div class="container">
<h1>Edit Subject</h1>
</div>

<div class="container">
    <div class="card border border-0" style="width: 400px;">
    <div class="mb-2">{{ include('subject/_form.html.twig', {'button_label': 'Update'}) }}</div>
    <div>{{ include('subject/_delete_form.html.twig') }}</div>
</div>
</div>

{% endblock %}

tutors-project/templates/subject/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Subjects{% endblock %}

{% block body %}
    <h1 class="text-center mt-5 mb-5">All Subjects</h1>

    <div class="container d-flex justify-content-center">
    <div class="row">
      {% for subject in subjects %}
        <div class="col">
            <div class="card border-dark mb-3 shadow-sm p-3 mb-5 bg-body rounded" style="width: 18rem;">
                <div class="card-header fw-bold">{{ subject.subjectName }}</div>
                  <div class="card-body d-flex">
                  {# <h6 class="card-subtitle mb-2 text-muted">{{ subject.id }}</h6> #}
                    <a href="{{ path('app_subject_show', {'id': subject.id}) }}" class="card-link btn btn-outline-success mt-2" role="button">Details</a>
                    <a href="{{ path('app_subject_edit', {'id': subject.id}) }}" class="card-link btn btn-outline-primary mt-2" role="button">Edit</a>
              </div>
            </div>
        </div>
        {% else %}
        <div>No records found.</div>
        {% endfor %}
    </div>
</div>

<div class="container d-flex justify-content-center">
  <a class="card-link btn btn-outline-dark mt-2" role="button" 
   href="{{ path('app_subject_new') }}">Create new</a>
  </div>

{% endblock %}

tutors-project/templates/subject/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Subject{% endblock %}

{% block body %}
<div class="container">
    <h1>Create new Subject</h1>
</div>

    <div class="container">
        <div class="card border border-0" style="width: 400px;">
    {{ include('subject/_form.html.twig') }}
</div>
    <a class="card-link btn mt-2" role="button" style="background-color: rgb(163, 193, 201);" href="{{ path('app_subject_index') }}">Go back to the list.</a>

</div>
{% endblock %}

tutors-project/templates/subject/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Subject{% endblock %}

{% block body %}

<h1 class="text-center mt-5 mb-5">Details</h1>

<div class="container d-flex justify-content-center">
<div class="row">
    <div class="col-sm-6">
        <div class="card border-dark mb-3 shadow-sm p-3 mb-5 bg-body rounded" style="width: 18rem;">
            <div class="card-header fw-bold">{{ subject.subjectName }}</div>
            <div class="card-body">
              <h6 class="card-subtitle mb-2 text-muted">Subject ID: {{ subject.id }}</h6>
              <br>
                    <a style="background-color: rgb(116, 200, 221);"  href="{{ path('app_subject_edit', {'id': subject.id}) }}" class="card-link btn " role="button">Edit</a>
               <br><br>
                    <a class="card-link btn" role="button" style="background-color: rgb(163, 193, 201);" href="{{ path('app_subject_index') }}">Go back to the list.</a>
            </div>
          </div>
    </div>
</div>
</div>
<div class="container d-flex justify-content-center">
    {{ include('subject/_delete_form.html.twig') }}
    </div>
{% endblock %}